baseURL = 'https://www.ty07.net'
DefaultContentLanguage = 'ja'
languageCode = 'ja-jp'
title = 'Not Good Father'

theme = 'anatole-ext'

paginate = 5

summarylength = 10
enableEmoji = true
enableInlineShortcodes = true
enableRobotsTXT = true
hasCJKLanguage = true
enableGitInfo = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

# Localized dates requires Hugo version 0.87.0
localizedDates = false

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[related]
  includeNewer = true
  threshold = 80
  toLower = true
[[related.indices]]
  name = 'keywords'
  weight = 100
[[related.indices]]
  name = 'tags'
  weight = 80
