baseURL = 'https://www.ty07.net'
title = 'Not Good Father'
DefaultContentLanguage = 'ja'
languageCode = 'ja-jp'
pagenate = '10'
theme = 'github-style'
enableEmoji = true
enableInlineShortcodes = true
enableGitInfo = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[Params]
  description = 'The sound, old pond and frog jump into water.'
  author = 'YAMASHITA, Takao'
  github = 'ac1965'
  twitter = 'ac1965'
  facebook = 'ac1965'
  instagram = 'tjy1965'
  email = 'ac1965@gmail.com'
  url = 'https://ty07.net'
  rss = true
  lastmod = true
  favicon = '/images/github.com'
  avatar = '/images/avatar.png'
  headerIcon = '/images/GitHub-Mark-Light-32px.png'
  location = 'Japan, /dev/urandom'
  enableGitalk = false

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
