baseURL = 'https://www.ty07.net'
DefaultContentLanguage = 'ja'
languageCode = 'ja-jp'
title = 'Not Good Father'

buildDrafts = false
buildFuture = false
buildExpired = false

pagenate = 5
enableRobotsTXT = true
enableEmoji = true
enableInlineShortcodes = true
enableGitInfo = true
pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsStyle = 'pastie'

theme = ['github-style']
# theme = 'anotale-ext'
# theme = 'PaperMod'

[Params]
  description = 'The sound, old pond and frog jump into water.'
  author = 'YAMASHITA, Takao'

  github = 'ac1965'
  twitter = 'ac1965'
  facebook = 'ac1965'
  instagram = 'tjy1965'
  email = 'tjy1965@gmail.com'
  url = 'https://www.ty07.net'
  rss = true
  lastmod = true
  favicon = '/images/github.com'
  avatar = '/images/avatar.png'
  headerIcon = '/images/GitHub-Mark-Light-32px.png'
  location = 'Japan, /dev/urandom'
  enableGitalk = false

[frontmatter]
   lastmod = ['lastmod', ':fileModTime', ':default']
