  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Archives"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[main]]
  name = "Tags"
  weight = 300
  identifier = "tags"
  url = "/tags/"

  [[main]]
  name = "About"
  weight = 400
  identifier = "about"
  url = "/readme/"
