  [[main]]
  name = "Archives"
  identifier = "archives"
  weight = 100
  url = "/archives/"

  [[main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[main]]
  name = "Search"
  weight = 300
  identifier = "search"
  url = "/search/"

  [[main]]
  name = "Tags"
  weight = 400
  identifier = "tags"
  url = "/tags/"

  [[main]]
  name = "About"
  weight = 500
  identifier = "about"
  url = "/readme/"
